### PR TITLE
Set HTTP timeouts

### LINKED ISSUE #32: No HTTP timeouts configured anywhere
This is an abstract of a memory dump: 

`pool-3-thread-1" #30 prio=5 os_prio=0 tid=0x00007ffc0c5c3000 nid=0x26 runnable [0x00007ffbe0337000]
 java.lang.Thread.State: RUNNABLE
 java.net.SocketInputStream.socketRead0(Native Method)
 java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
 java.net.SocketInputStream.read(SocketInputStream.java:170)
 java.net.SocketInputStream.read(SocketInputStream.java:141)
 sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
 sun.security.ssl.InputRecord.read(InputRecord.java:503)
 sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
locked <0x00000007089d55e0> (a java.lang.Object)
 sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
locked <0x00000007089d5708> (a java.lang.Object)
 sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
 sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
 org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:543)
 org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
 org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
 org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
 org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
 org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
 org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
 org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
 org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
 clj_http.core$request.invoke(core.clj:298)
 clojure.lang.Var.invoke(Var.java:379)
 clj_http.client$wrap_request_timing$fn__2908.invoke(client.clj:796)
 clj_http.headers$wrap_header_map$fn__983.invoke(headers.clj:143)
 clj_http.client$wrap_query_params$fn__2821.invoke(client.clj:624)
 clj_http.client$wrap_basic_auth$fn__2828.invoke(client.clj:640)
 clj_http.client$wrap_oauth$fn__2832.invoke(client.clj:647)
 clj_http.client$wrap_user_info$fn__2837.invoke(client.clj:663)
 clj_http.client$wrap_url$fn__2894.invoke(client.clj:762)
 clj_http.client$wrap_redirects$fn__2649.invoke(client.clj:237)
 clj_http.client$wrap_decompression$fn__2668.invoke(client.clj:309)
 clj_http.client$wrap_input_coercion$fn__2760.invoke(client.clj:460)
 clj_http.client$wrap_additional_header_parsing$fn__2781.invoke(client.clj:522)
 clj_http.client$wrap_output_coercion$fn__2751.invoke(client.clj:438)
 clj_http.client$wrap_exceptions$fn__2635.invoke(client.clj:189)
 clj_http.client$wrap_accept$fn__2795.invoke(client.clj:565)
 clj_http.client$wrap_accept_encoding$fn__2801.invoke(client.clj:579)
 clj_http.client$wrap_content_type$fn__2790.invoke(client.clj:554)
 clj_http.client$wrap_form_params$fn__2872.invoke(client.clj:722)
 clj_http.client$wrap_nested_params$fn__2889.invoke(client.clj:755)
 clj_http.client$wrap_method$fn__2842.invoke(client.clj:670)
 clj_http.cookies$wrap_cookies$fn__266.invoke(cookies.clj:124)
 clj_http.links$wrap_links$fn__1167.invoke(links.clj:51)
 clj_http.client$wrap_unknown_host$fn__2898.invoke(client.clj:771)
 clj_http.client$post.doInvoke(client.clj:886)
 clojure.lang.RestFn.invoke(RestFn.java:423)
 org.zalando.stups.mint.worker.external.services$generate_new_password.invoke(services.clj:36)
 org.zalando.stups.mint.worker.job.sync_password$sync_password.invoke(sync_password.clj:26)
 org.zalando.stups.mint.worker.job.sync_app$sync_app.invoke(sync_app.clj:38)
 org.zalando.stups.mint.worker.job.run$run_sync$fn__6870.invoke(run.clj:48)
 org.zalando.stups.mint.worker.job.run$run_sync.invoke(run.clj:47)
 org.zalando.stups.mint.worker.job.run.Jobs$fn__6917$fn__6918$fn__6919.invoke(run.clj:85)
 clojure.lang.AFn.call(AFn.java:18)
 org.zalando.stups.txdemarcator.Transactions.runAsBackgroundTransaction(Transactions.java:55)
 org.zalando.stups.mint.worker.job.run.Jobs$fn__6917$fn__6918.invoke(run.clj:85)
 org.zalando.stups.friboo.system.cron.NewRelicTracer.callWithTrace(cron.clj:54)
 sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:497)
 clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
 clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
 org.zalando.stups.mint.worker.job.run.Jobs$fn__6917.invoke(run.clj:85)
 clojure.lang.AFn.run(AFn.java:22)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
 java.lang.Thread.run(Thread.java:745)`

at `org.zalando.stups.mint.worker.external.services$generate_new_password.invoke(services.clj:36)` it seems to hang.

There should be some timeout setting for these cases

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #32 

Sets both connection and socket timeout to 10 seconds (please advise if other value is better). Hope hardcoded value is ok.

Apache HTTP Client version in mint-worker (@jbellmann's comment) should be fine, is `4.5.1`.

### CODE REVIEW

File: src/org/zalando/stups/mint/worker/external/http.clj [hunk 1]
```diff
@@ -0,0 +1,21 @@
+(ns org.zalando.stups.mint.worker.external.http
+  (:require [clj-http.client :as client]))
+
+(def ^:private default-http-options
+  {:socket-timeout 10000
```
Comment (hjacobs) [inline src/org/zalando/stups/mint/worker/external/http.clj]: Is 10s enough for every use case in mint-worker? We could increase it to 30s or even 60s I would say to catch any latency spikes or slow network. The whole mint worker is just asynchronous job, so it's better to complete in 30s successfully than failing early after 10s (as no "customer" is waiting). The goal is just to have "some reasonable" timeouts instead of none.

**Review by hjacobs — CHANGES_REQUESTED** [review]
Please check the default timeouts, I think we can increase them.

**Comment by prayerslayer** [comment]
Increased timeouts to one minute.

**Review by hjacobs — APPROVED** [review]

**Comment by hjacobs** [comment]
:+1:

**Review by vroldanbet — APPROVED** [review]

**Comment by vroldanbet** [comment]
:+1:
